---
title: "analysis_work"
author: "Max Callaghan"
date: "December 2, 2015"
output: html_document
---

```{r warning=FALSE,message=FALSE,echo=FALSE}

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

load("data/merged_corpus_europe.rda")

library(knitr)
library(dplyr)
library(rworldmap)
library(ggmap)
pkgs <- c('twitteR', 'tm.lexicon.GeneralInquirer', 'tm.plugin.sentiment', 'dplyr', 'ggplot2', 'stringr', 'wordcloud', 'tm', 'rworldmap', 'ggmap','ggvis','googleVis')
library(ggvis)
library(googleVis)
library(tidyr)
library(ggplot2)

spacetime <- function(df,q) {
  df <- df %>%
  filter(query==q) %>%
  group_by(approx_country) %>%
  summarise(
    p1 = mean(stotal[period=="2010"],na.rm=TRUE),
    p2 = mean(stotal[period=="2012"],na.rm=TRUE),
    p3 = mean(stotal[period=="2015"],na.rm=TRUE)
  ) 
  return(df)
}

greek_greece_debt <- merged_corpus_europe %>%
  filter(query %in% c("greek+debt","greece+debt")) %>%
  mutate(query="greek_greece_debt") 

greek_greece_debt <- greek_greece_debt[!duplicated(greek_greece_debt$tweet_id),]

merged_corpus_europe <- rbind(merged_corpus_europe,greek_greece_debt)

merged_corpus_europe$day <- as.Date(substr(as.character(merged_corpus_europe$date),1,10))

merged_corpus_daily_queries <- merged_corpus_europe %>%
  group_by(day,period,approx_country,query) %>%
  summarise(
    sentiment = mean(stotal,na.rm=TRUE),
    sentiment_variance = var(stotal,na.rm=TRUE),
    tweet_count = length(stotal)
  )

merged_corpus_daily <- merged_corpus_europe %>%
  group_by(day,period,approx_country) %>%
  summarise(
    sentiment = mean(stotal,na.rm=TRUE),
    sentiment_variance = var(stotal,na.rm=TRUE),
    tweet_count = length(stotal)
  )

sentiment_time <- function(df,p,q=NULL,clist=NULL) {
  df <- filter(df,period==p)
  if(!is.null(q)) {
    df <- filter(df,query==q)
  }
  if(!is.null(clist)){
    df <- filter(df,approx_country %in% clist)
  }
  ggplot(df) + 
  geom_line(aes(day,sentiment,colour=approx_country)) +
  geom_ribbon(aes(
    day,
    ymin=sentiment-sqrt(sentiment_variance),
    ymax=sentiment+sqrt(sentiment_variance),
    fill=approx_country),alpha=0.2) +
  labs(
    x = "Time",
    y = "Sentiment"
  )
}


sentiment_time(merged_corpus_daily,"2015",clist=c("GR","DE"))
sentiment_time(merged_corpus_daily,"2015",clist=c("GR"))
sentiment_time(merged_corpus_daily_queries,"2015",q="greek_greece_debt",clist=c("GR","DE"))
sentiment_time(merged_corpus_daily_queries,"2015",q="greek_greece_debt",clist=c("GR","DE"))
sentiment_time(merged_corpus_daily_queries,"2015",q="greek+crisis",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="varoufakis",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="merkel+greece",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="schäuble+greece",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="austerity+greece",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="eurocrisis",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="eurosummit",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="euro+summit",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="euro+summit",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="grexit",clist=c("GR","DE"))

sentiment_time(merged_corpus_daily_queries,"2015",q="tsipras",clist=c("GR","DE"))

ggplot(merged_corpus_europe,aes(query)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


timegraph <- function(corpus,p) {
  corpus_daily <- corpus %>%
    filter(period==p) %>%
  group_by(day,query,period) %>%
  summarise(
    n = length(day)
  )
  
ggplot(filter(corpus_daily), aes(day,n,colour=query)) + geom_line() +
  labs(
    x = "Time",
    y = "Frequency"
  )
}



print(unique(merged_corpus_europe$query))

geo_corpus <- merged_corpus_europe %>%
  filter(!is.na(latitude))

map_eu <- get_map(zoom = 4, location= "Europe")
mapPoints <- ggmap(map_eu) +
  geom_point(aes(x = longtitude, y = latitude, colour = query),size=1.8, data = geo_corpus) +
  geom_jitter()
mapPoints

by_country_by_year_by_query <- merged_corpus_europe %>%
  group_by(approx_country,period,query) %>%
  summarise(
    sentiment = mean(stotal,na.rm=TRUE),
    sentiment_variance = var(stotal,na.rm=TRUE),
    tweet_count = length(stotal)
  ) %>%
  mutate(query = gsub("\\+","_",query))

library(rjson)
for (countries in unique(by_country_by_year_by_query$approx_country)) {
  
}
ys <- split(by_country_by_year_by_query,by_country_by_year_by_query$period)
for (y in ys) {
  xs <- split(y,y$approx_country)
  for (x in xs) {
    z <- split(x,x$query)
    cat(toJSON(unname(z)))
  }
  x <- toJSON(unname(split(y,y$approx_country)))
  #cat(x)
  #print(unique(as.character(y$period))) 
}
x <- toJSON(unname(split(by_country_by_year_by_query, 1:nrow(by_country_by_year_by_query ))))
write(x, file="map/map_data.JSON")

by_country_by_year <- by_country_by_year_by_query %>%
  select(-sentiment_variance,-tweet_count) %>%
  spread(query,sentiment)

by_country_by_year_var <- by_country_by_year_by_query %>%
  select(-sentiment,-tweet_count) %>%
  spread(query,sentiment_variance)

by_country_by_year_count <- by_country_by_year_by_query %>%
  select(-sentiment_variance,-sentiment) %>%
  spread(query,tweet_count)

place_reg <- lm(sentiment~approx_country,data=by_country_by_year_by_query)
summary(place_reg)

time_reg <- lm(sentiment~period,data=by_country_by_year_by_query)
summary(time_reg)

all_reg <- lm(sentiment~approx_country+period,data=by_country_by_year_by_query)
summary(time_reg)

```

We compare each tweet with a lexicon of words categorised as expressing positive and negative sentiment. Each tweet gets a score according to how many positive words it has and how many negative.



## IMF + GREECE

```{r warning=FALSE,message=FALSE,cache=TRUE,echo=FALSE}

library(dplyr)
library(tidyr)
library(lfe)
library(maptools)
library(rgeos)

library(nlme)

countries <- readShapeSpatial("data/geographic_data/CNTR_2014_60M_SH/Data/CNTR_RG_60M_2014.shp")

#countries@data$id <- countries@data$CNTR_ID
countries.points <- fortify(countries)
countries.points <- left_join(
  countries.points,
  data.frame(
    id = unique(countries.points$id),
    CNTR_ID = unique(countries@data$CNTR_ID)
  )
)
countries.df <- countries.points %>%
  left_join(countries@data,by="CNTR_ID")

countries.df$CNTR_ID <- as.character(countries.df$CNTR_ID)

countries.df[countries.df$CNTR_ID=="UK","CNTR_ID"] <- "GB"
countries.df[countries.df$CNTR_ID=="EL","CNTR_ID"] <- "GR"

countries.variance <- countries.df %>%
  left_join(
    rename(
      by_country_by_year_var,
      CNTR_ID = approx_country
      )
  ) 

countries.df <- countries.df %>%
  left_join(
    rename(
      by_country_by_year,
      CNTR_ID = approx_country
      )
  ) 

sentiment_map <- function(df,p,q,v=FALSE) {
    if(v==FALSE){
      cscale <- scale_fill_gradientn(colours=c("red","white","green"),limits=c(-2,2),na.value="grey")
      label <- "Sentiment"
    } else {
      cscale <- scale_fill_gradientn(colours=c("white","green"),limits=c(0,4),na.value="grey")
      label <- "Sentiment \nVariance"
    }
  ggplot(filter(df,period==p))+
  aes_string("long","lat",group="group",fill=q) +
  cscale +
  #scale_fill_gradientn(colours=c("red","white","green"),limits=c(-2,2)) +
  geom_polygon() +
  #scale_fill_continuous(low="white",high="green",na.value="grey") +
  geom_path(color="grey",size=0.1) +
  #theme_bw() +
  #theme_nothing() +
  theme(
    panel.background = element_rect(fill="#84C9F8"),
    axis.text = element_blank(),
    line = element_blank(),
    axis.text = element_blank()
  ) +
  xlim(c(-12,35)) +
  ylim(c(32,72)) +
  labs(fill=label,x="",y="") + 
  coord_equal()
}

s <- sentiment_map(countries.df,"2010","greek_greece_debt")
v <- sentiment_map(countries.variance,"2010","greek_greece_debt",v=TRUE)
multiplot(s,v)
kable(select(filter(by_country_by_year_count,period=="2010"),approx_country,greek_greece_debt))
s <- sentiment_map(countries.df,"2012","greek_greece_debt")
v <- sentiment_map(countries.variance,"2012","greek_greece_debt",v=TRUE)
multiplot(s,v)
kable(select(filter(by_country_by_year_count,period=="2010"),approx_country,greek_greece_debt))
s <- sentiment_map(countries.df,"2015","greek_greece_debt")
v <- sentiment_map(countries.variance,"2015","greek_greece_debt",v=TRUE)
multiplot(s,v)
kable(select(filter(by_country_by_year_count,period=="2010"),approx_country,greek_greece_debt))



sentiment_map(countries.df,"2010","imf_greece")
sentiment_map(countries.df,"2012","imf_greece")
sentiment_map(countries.df,"2015","imf_greece")

sentiment_map(countries.variance,"2010","imf_greece",v=TRUE)
sentiment_map(countries.variance,"2012","imf_greece",v=TRUE)
sentiment_map(countries.variance,"2015","imf_greece",v=TRUE)


sentiment_map(countries.df,"2010","greek_debt")
sentiment_map(countries.df,"2012","greek_debt")
sentiment_map(countries.df,"2015","greek_debt")

sentiment_map(countries.df,"2010","greece_debt")
sentiment_map(countries.df,"2012","greece_debt")
sentiment_map(countries.df,"2015","greece_debt")


sentiment_map(countries.df,"2010","bailout_greece")
sentiment_map(countries.df,"2012","bailout_greece")
sentiment_map(countries.df,"2015","bailout_greece")

sentiment_map(countries.df,"2010","eurogroup")
sentiment_map(countries.df,"2012","eurogroup")
sentiment_map(countries.df,"2015","eurogroup")

sentiment_map(countries.variance,"2010","eurogroup",v=TRUE)
sentiment_map(countries.variance,"2012","eurogroup",v=TRUE)
sentiment_map(countries.variance,"2015","eurogroup",v=TRUE)

```

## Austerity + Greece

```{r warning=FALSE,message=FALSE,cache=TRUE,echo=FALSE}

sentiment_map(countries.df,"2010","austerity_greece")
sentiment_map(countries.df,"2012","austerity_greece")
sentiment_map(countries.df,"2015","austerity_greece")

```

## Schäuble + Greece

```{r warning=FALSE,message=FALSE,cache=TRUE,echo=FALSE}

sentiment_map(countries.df,"2010","schäuble_greece")
sentiment_map(countries.df,"2012","schäuble_greece")
sentiment_map(countries.df,"2015","schäuble_greece")

```
