---
title: 'Twitter and the European Hyperagora: What can the Twittersphere Tell us about Political Deliberation and Opinions in Europe?'
author: "M. Callaghan, V. Nieberg"
date: "November 14, 2015"
output: html_document
---

1500 words

# Data Gathering 


# Data Cleaning  

```{r}
library(ggplot2)

files <- list.files("data/GOToutput")

corpus <- data.frame()

for (file in files) {
  df <- read.delim(paste0("data/GOToutput/",file),
                   quote="")
  query <- strsplit(file,"_")[[1]][1]
  period <- paste0(strsplit(file,"_")[[1]][2],"-",strsplit(file,"_")[[1]][3])
  df$query <- query
  df$period <- period
  corpus <- rbind(corpus,df)
}

ggplot(corpus,aes(query)) + geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(corpus,aes(query,fill=period)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

users <- unique(corpus$user_id)

```


# Data Analysis

## Descriptive Statistics

```{r}
library(ggplot2)
library(dplyr)
library(stringr)
corpus <- read.csv('data/corpus.csv')
eurocrisis <- filter(corpus, query == 'eurocrisis')

corpus <- filter(corpus,query!="2-pac"&query!="3-pac")

eurocrisis$day <- as.Date(substr(as.character(eurocrisis$date),1,10))

eurocrisis_daily <- eurocrisis %>%
  group_by(day) %>%
  summarise(
    n = length(day)
  )

corpus$day <- as.Date(substr(as.character(corpus$date),1,10))

corpus_index <- corpus %>%
  group_by(query) %>%
  summarise(total = length(query))

corpus_index_large <- filter(corpus_index,total>10000)
corpus_index_small <- filter(corpus_index,total<10000)

corpus_large <- filter(corpus,query %in% corpus_index_large$query)

corpus_small <- filter(corpus,query %in% corpus_index_small$query)

timegraph(corpus_large)

timegraph <- function(corpus,p) {
  corpus_daily <- corpus %>%
    filter(period==p) %>%
  group_by(day,query,period) %>%
  summarise(
    n = length(day)
  )

ggplot(filter(corpus_daily), aes(day,n,colour=query)) + geom_line() +
  scale_x_date(format("%b-%Y")) +
  ggtitle(p)

}

timegraph(corpus_small,"2010-04-15-2010-05-15.txt")
timegraph(corpus_small,"2012-02-07-2012-03-31.txt")
timegraph(corpus_small,"2015-07-01-2015-08-25.txt")

timegraph(corpus_large,"2010-04-15-2010-05-15.txt")
timegraph(corpus_large,"2012-02-07-2012-03-31.txt")
timegraph(corpus_large,"2015-07-01-2015-08-25.txt")




```



## Inferential Statistics

